### ISSUE TITLE
how to do it on images i have?

### ISSUE THREAD

**Issue by mayankgarg1306** [bigpas/face_exp_analysis#1]
Is there any way to get the characteristics which you have in raw data  for the images stored locally.
plzz help.

**Comment by bigpas** [comment]
Hello,

thank you for your question.
However, I am not sure I understand what you mean:
this little package is processing results from the iMOTIONS FACET (see
https://imotions.com/emotient/) not raw images.
Does it make sense?

Best,

**Comment by mayankgarg1306** [comment]
ok now i understood,
actually i want to do this on the image files directly
